# Starter pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/microservicesDeployment

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  demands: maven

  timeoutInMinutes: 30

variables:
  ACR_NAME: 'MicroServiceACR'
  AKS_RG: 'MicroServiceRG'
  AKS_CLUSTER: 'devaks'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    java -version
    mvn -version
  displayName: "Verify Java version"
- task: AzureCLI@2
  displayName: 'Login To ACR'
  inputs:
    azureSubscription: 'AZ-Pipeline-Service-Connection-MS'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Login ACR
           az acr login --name $(ACR_NAME)
     
      # Get AKS credentials
           az aks get-credentials --resource-group $(AKS_RG)  --name $(AKS_CLUSTER) overwrite-existing
- task: Maven@4
  displayName: 'ACR Image genration'
  inputs:
    azureSubscription: 'AZ-Pipeline-Service-Connection-MS'
    mavenPomFile: section6/v2-spring-cloud-config/accounts/pom.xml
    goals: 'compile jib:build'
    options: '-Djib.to.image=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest'
    publishJUnitResults: false

- task: AzureCLI@2
  displayName: 'Get AKS Credentials to deploy in next'
  inputs:
    azureSubscription: 'AZ-Pipeline-Service-Connection-MS'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'az aks get-credentials --resource-group $(AKS_RG) --name $(AKS_CLUSTER) --overwrite-existing'

- task: KubernetesManifest@1
  displayName: deploy
  inputs:
    connectionType: azureResourceManager
    azureSubscriptionConnection: 'AZ-Pipeline-Service-Connection-MS'
    azureResourceGroup: devTestacraks
    kubernetesCluster: devaks
    useClusterAdmin: true
    namespace: default
    manifests: azurePoc/Deployment.yml
    containers: '  devestacraks.azurecr.io/azurepoc:latest'
    imagePullSecrets: 'az aks update --name devaks --resource-group  devTestacraks --attach-acr devestacraks'



